<a href="https://colab.research.google.com/github/nogiator/Hamoye/blob/master/Hamoye_Stage_C_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing libraries

import numpy as np
import pandas as pd
import sklearn
import math
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors
%matplotlib inline


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
# Importing dataset into a dataframe

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Data_for_UCI_named.csv')
df.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [3]:
df.drop('stab', inplace=True, axis=1)
df.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [4]:
from sklearn.metrics import recall_score, accuracy_score, f1_score, confusion_matrix

x = df.drop('stabf', axis=1)
y = df.stabf

In [5]:
# train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [6]:
# Standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_trainscale = scaler.transform(x_train)
x_testscale = scaler.transform(x_test)

In [7]:
x_trainscale1 = pd.DataFrame(x_trainscale, columns = x_train.columns)
x_testscale1 = pd.DataFrame(x_testscale, columns = x_test.columns)

In [8]:
# Using the random forest classifier
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state=1)


In [9]:
rfc.fit(x_trainscale1, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [10]:
rfc_pred=rfc.predict(x_testscale1)

In [11]:
y_test.unique()

array(['unstable', 'stable'], dtype=object)

In [12]:
from sklearn.metrics import accuracy_score, classification_report
print(classification_report(y_test, rfc_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9191    0.8778    0.8980       712
    unstable     0.9341    0.9573    0.9456      1288

    accuracy                         0.9290      2000
   macro avg     0.9266    0.9176    0.9218      2000
weighted avg     0.9288    0.9290    0.9286      2000



In [13]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
cnf_mat = confusion_matrix(y_test, rfc_pred, labels=['unstable', 'stable'])
cnf_mat

array([[1233,   55],
       [  87,  625]])

In [14]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, rfc_pred)
accuracy

0.929

In [15]:
recall = recall_score(y_test, rfc_pred, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 88.0


In [16]:
precision = precision_score(y_test, rfc_pred, pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 92.0


In [17]:
f1 = f1_score(y_test, rfc_pred, pos_label='stable')
print('f1: {}'.format(round(f1*100), 2))

f1: 90.0


In [18]:
# Using the extra trees classifier
from sklearn.ensemble import ExtraTreesClassifier
ETC = ExtraTreesClassifier(random_state=1)

In [19]:
ETC.fit(x_trainscale1, y_train)
ETC_pred = ETC.predict(x_testscale1)
print(classification_report(y_test, ETC_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9410    0.8511    0.8938       712
    unstable     0.9218    0.9705    0.9455      1288

    accuracy                         0.9280      2000
   macro avg     0.9314    0.9108    0.9197      2000
weighted avg     0.9287    0.9280    0.9271      2000



In [20]:
cnf_mat1 = confusion_matrix(y_test, ETC_pred)
cnf_mat1

array([[ 606,  106],
       [  38, 1250]])

In [21]:
accuracy1 = accuracy_score(y_test, ETC_pred)
print('Accuracy1: {}'.format(round(accuracy1*100), 2))


Accuracy1: 93.0


In [22]:
recall1 = recall_score(y_test, ETC_pred, pos_label='stable')
print('Recall1: {}'.format(round(recall1*100), 2))

Recall1: 85.0


In [23]:
precision1 = precision_score(y_test, ETC_pred, pos_label='stable')
print('Precision1: {}'.format(round(precision1*100), 2))

Precision1: 94.0


In [24]:
f11 = f1_score(y_test, ETC_pred, pos_label='stable')
print('F11: {}'.format(round(f11*100), 2))

F11: 89.0


In [25]:
# Using the xg boost classifier
from xgboost import XGBClassifier
XGB = XGBClassifier(random_state=1)
XGB.fit(x_trainscale1, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [26]:
XGB_pred = XGB.predict(x_testscale1)
print(classification_report(y_test, XGB_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9206    0.8469    0.8822       712
    unstable     0.9190    0.9596    0.9389      1288

    accuracy                         0.9195      2000
   macro avg     0.9198    0.9033    0.9105      2000
weighted avg     0.9195    0.9195    0.9187      2000



In [27]:
cnf_mat2 = confusion_matrix(y_test, XGB_pred)
cnf_mat2

array([[ 603,  109],
       [  52, 1236]])

In [28]:
accuracy2 = accuracy_score(y_test, XGB_pred)
print('Accuracy2: {}'.format(round(accuracy2*100), 3))

Accuracy2: 92.0


In [30]:
recall2 = recall_score(y_test, XGB_pred, pos_label='stable')
print('Recall2: {}'.format(round(recall2*100), 2))

Recall2: 85.0


In [31]:
precision2 = precision_score(y_test, XGB_pred, pos_label='stable')
print('Precision2: {}'.format(round(precision2*100), 2))

Precision2: 92.0


In [32]:
f12 = f1_score(y_test, XGB_pred, pos_label='stable')
print('F12: {}'.format(round(f12*100), 2))

F12: 88.0


In [33]:
# Using the lightgbm classifier
from lightgbm import LGBMClassifier
LGBM = LGBMClassifier(random_state=1)
LGBM.fit(x_trainscale1, y_train)
LGBM_pred = LGBM.predict(x_testscale1)
print(classification_report(y_test, LGBM_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9297    0.8919    0.9104       712
    unstable     0.9415    0.9627    0.9520      1288

    accuracy                         0.9375      2000
   macro avg     0.9356    0.9273    0.9312      2000
weighted avg     0.9373    0.9375    0.9372      2000



In [34]:
cnf_mat3 = confusion_matrix(y_test, LGBM_pred)
cnf_mat3

array([[ 635,   77],
       [  48, 1240]])

In [35]:
accuracy3 = accuracy_score(y_test, LGBM_pred)
print('Accuracy3: {}'.format(round(accuracy3*100), 3))

Accuracy3: 94.0


In [36]:
recall3 = recall_score(y_test, LGBM_pred, pos_label='stable')
print('Recall3: {}'.format(round(recall3*100), 2))

Recall3: 89.0


In [37]:
precision3 = precision_score(y_test, LGBM_pred, pos_label='stable')
print('Precision3: {}'.format(round(precision3*100), 2))

Precision3: 93.0


In [38]:
f13 = f1_score(y_test, LGBM_pred, pos_label='stable')
print('F13: {}'.format(round(f13*100), 2))

F13: 91.0
